name: Unit Tests

on:
  push:
    branches: [ master ]
    paths: '**.jl'
  pull_request:
    branches: [ master ]

jobs:
  julia-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    # Checks-out repository under $GITHUB_WORKSPACE
    - name: Checkout Project
      uses: actions/checkout@v2
    - name: Setup Julia environment
      uses: julia-actions/setup-julia@v1.1.12
      with:
        version: 1.5
        arch: x64
    - name: Load Julia Packages
      uses: julia-actions/julia-buildpkg@latest
    - name: Run Test Suite
      uses: julia-actions/julia-runtest@latest
